trying to use build from sklearn

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -13,120 +13,156 @@ concurrency:
   group: deploy-${{ github.ref }}
   cancel-in-progress: true
 
+
 jobs:
+  # Build the wheels for Linux, Windows and macOS for Python 3.9 and newer
   build_wheels:
+    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
     runs-on: ${{ matrix.os }}
+    needs: check_build_trigger
+    if: needs.check_build_trigger.outputs.build
+
     strategy:
+      # Ensure that a wheel builder finishes even if another fails
       fail-fast: false
       matrix:
         include:
-          # Windows 64-bit
+          # Window 64 bit
           - os: windows-latest
-            archs: AMD64
-            python: 3.9
+            python: 39
+            platform_id: win_amd64
           - os: windows-latest
-            archs: AMD64
-            python: 3.10
+            python: 310
+            platform_id: win_amd64
           - os: windows-latest
-            archs: AMD64
-            python: 3.11
+            python: 311
+            platform_id: win_amd64
           - os: windows-latest
-            archs: AMD64
-            python: 3.12
+            python: 312
+            platform_id: win_amd64
 
-          # Linux 64-bit
+          # Linux 64 bit manylinux2014
           - os: ubuntu-latest
-            archs: x86_64
-            python: 3.9
-          - os: ubuntu-latest
-            archs: x86_64
-            python: 3.10
-          - os: ubuntu-latest
-            archs: x86_64
-            python: 3.11
-          - os: ubuntu-latest
-            archs: x86_64
-            python: 3.12
+            python: 39
+            platform_id: manylinux_x86_64
+            manylinux_image: manylinux2014
 
-          # Linux aarch64
+          # NumPy on Python 3.10 only supports 64bit and is only available with manylinux2014
           - os: ubuntu-latest
-            archs: aarch64
-            python: 3.9
-          - os: ubuntu-latest
-            archs: aarch64
-            python: 3.10
-          - os: ubuntu-latest
-            archs: aarch64
-            python: 3.11
-          - os: ubuntu-latest
-            archs: aarch64
-            python: 3.12
+            python: 310
+            platform_id: manylinux_x86_64
+            manylinux_image: manylinux2014
 
-          # macOS x86_64
-          - os: macos-latest
-            archs: x86_64
-            python: 3.9
-          - os: macos-latest
-            archs: x86_64
-            python: 3.10
-          - os: macos-latest
-            archs: x86_64
-            python: 3.11
-          - os: macos-latest
-            archs: x86_64
-            python: 3.12
+          - os: ubuntu-latest
+            python: 311
+            platform_id: manylinux_x86_64
+            manylinux_image: manylinux2014
+          - os: ubuntu-latest
+            python: 312
+            platform_id: manylinux_x86_64
+            manylinux_image: manylinux2014
+          - os: ubuntu-latest
+            python: 313t
+            platform_id: manylinux_x86_64
+            manylinux_image: manylinux2014
+            # TODO: remove next line when Python 3.13 is released
+            prerelease_pythons: True
+            free_threaded_support: True
 
-          # macOS arm64
-          - os: macos-latest
-            archs: arm64
-            python: 3.9
-          - os: macos-latest
-            archs: arm64
-            python: 3.10
-          - os: macos-latest
-            archs: arm64
-            python: 3.11
-          - os: macos-latest
-            archs: arm64
-            python: 3.12
+          # MacOS x86_64
+          - os: macos-12
+            python: 39
+            platform_id: macosx_x86_64
+          - os: macos-12
+            python: 310
+            platform_id: macosx_x86_64
+          - os: macos-12
+            python: 311
+            platform_id: macosx_x86_64
+          - os: macos-12
+            python: 312
+            platform_id: macosx_x86_64
+
+          # MacOS arm64
+          - os: macos-14
+            python: 39
+            platform_id: macosx_arm64
+          - os: macos-14
+            python: 310
+            platform_id: macosx_arm64
+          - os: macos-14
+            python: 311
+            platform_id: macosx_arm64
+          - os: macos-14
+            python: 312
+            platform_id: macosx_arm64
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout wordllama
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
-          python-version: ${{ matrix.python }}
+          python-version: "3.11" # update once build dependencies are available
 
-      - name: Install required Python packages
+      - name: Install conda for macos arm64
+        if: ${{ matrix.platform_id == 'macosx_arm64' }}
         run: |
-          python -m pip install --upgrade pip setuptools wheel cython
-          python -m pip install 'cibuildwheel>=2.2.0' twine
+          set -ex
+          # macos arm64 runners do not have conda installed. Thus we much install conda manually
+          EXPECTED_SHA="dd832d8a65a861b5592b2cf1d55f26031f7c1491b30321754443931e7b1e6832"
+          MINIFORGE_URL="https://github.com/conda-forge/miniforge/releases/download/23.11.0-0/Mambaforge-23.11.0-0-MacOSX-arm64.sh"
+          curl -L --retry 10 $MINIFORGE_URL -o miniforge.sh
 
-      - name: Set up QEMU to build non-native architectures
-        if: ${{ matrix.archs == 'aarch64' }}
-        uses: docker/setup-qemu-action@v3
+          # Check SHA
+          file_sha=$(shasum -a 256 miniforge.sh | awk '{print $1}')
+          if [ "$EXPECTED_SHA" != "$file_sha" ]; then
+              echo "SHA values did not match!"
+              exit 1
+          fi
 
-      - name: Build wheels
-        uses: pypa/cibuildwheel@v2.19.2
+          # Install miniforge
+          MINIFORGE_PATH=$HOME/miniforge
+          bash ./miniforge.sh -b -p $MINIFORGE_PATH
+          echo "$MINIFORGE_PATH/bin" >> $GITHUB_PATH
+          echo "CONDA_HOME=$MINIFORGE_PATH" >> $GITHUB_ENV
+
+      - name: Set conda environment for non-macos arm64 environments
+        if: ${{ matrix.platform_id != 'macosx_arm64' }}
+        run: |
+          # Non-macos arm64 envrionments already have conda installed
+          echo "CONDA_HOME=/usr/local/miniconda" >> $GITHUB_ENV
+
+      - name: Build and test wheels
         env:
-          CIBW_ARCHS: ${{ matrix.archs }}
-          CIBW_SKIP: |
-            cp38-musllinux_* 
-            pp38-* 
-            pp*-manylinux_i686
-            macosx_arm64_python3.8
-            aarch64_pp*
+          CIBW_PRERELEASE_PYTHONS: ${{ matrix.prerelease_pythons }}
+          CIBW_FREE_THREADED_SUPPORT: ${{ matrix.free_threaded_support }}
+          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
+          CIBW_ARCHS: all
+          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
+          CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
+          # Needed on Windows CI to compile with Visual Studio compiler
+          # otherwise Meson detects a MINGW64 platform and use MINGW64
+          # toolchain
+          CIBW_CONFIG_SETTINGS_WINDOWS: "setup-args=--vsenv"
+            #CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: bash build_tools/github/repair_windows_wheels.sh {wheel} {dest_dir}
+            #CIBW_BEFORE_TEST_WINDOWS: bash build_tools/github/build_minimal_windows_image.sh ${{ matrix.python }}
+            #CIBW_BEFORE_TEST: bash {project}/build_tools/wheels/cibw_before_test.sh
+            #CIBW_TEST_REQUIRES: pytest pandas
+            #CIBW_TEST_COMMAND: bash {project}/build_tools/wheels/test_wheels.sh
+            #CIBW_TEST_COMMAND_WINDOWS: bash {project}/build_tools/github/test_windows_wheels.sh ${{ matrix.python }}
+          CIBW_BUILD_VERBOSITY: 1
 
-      - name: Check packages
-        run: twine check dist/*
+        run: bash build_wheels.sh
 
-      - uses: actions/upload-artifact@v4
+      - name: Store artifacts
+        uses: actions/upload-artifact@v4
         with:
-          name: "packages-${{ matrix.os }}-${{ matrix.archs }}"
-          path: dist/
+          name: cibw-wheels-cp${{ matrix.python }}-${{ matrix.platform_id }}
+          path: wheelhouse/*.whl
 
   build_sdist:
     runs-on: ubuntu-latest
